# Generated by Django 2.1.1 on 2020-06-16 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0042_auto_20200616_1028'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ea', '0023_sign_is_pushed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('0', '결재'), ('1', '합의'), ('2', '수신및참조')], default='0', max_length=2)),
                ('order', models.PositiveSmallIntegerField()),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employee.Employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='signgroup',
            name='signs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ea.SignList'),
        ),
        migrations.AddField(
            model_name='signgroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sign_group', to=settings.AUTH_USER_MODEL),
        ),
    ]
