# Generated by Django 2.1.1 on 2020-06-18 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ea', '0026_auto_20200616_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signlist',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sign_lists', to='ea.SignGroup'),
        ),
    ]
