# Generated by Django 2.1.1 on 2020-06-23 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ea', '0028_auto_20200623_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cc',
            old_name='isReaded',
            new_name='is_readed',
        ),
    ]
