# Generated by Django 2.1.1 on 2020-06-23 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ea', '0029_auto_20200623_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cc',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_copys_lists', to='employee.Employee'),
        ),
        migrations.AlterField(
            model_name='defaulsignlist',
            name='type',
            field=models.CharField(choices=[('0', '결재'), ('1', '합의'), ('2', '수신참조')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='sign',
            name='type',
            field=models.CharField(choices=[('0', '결재'), ('1', '합의'), ('2', '수신참조')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='signlist',
            name='type',
            field=models.CharField(choices=[('0', '결재'), ('1', '합의'), ('2', '수신참조')], default='0', max_length=2),
        ),
    ]
