# Generated by Django 2.1.1 on 2020-07-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ea', '0030_auto_20200623_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_readed_after_finishing',
            field=models.BooleanField(default=False),
        ),
    ]
