# Generated by Django 2.1.1 on 2020-08-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ea', '0031_document_is_readed_after_finishing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='RPZ5CREDITAT',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPZ5DEBITAT',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
